# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_with_friends', '0004_auto_20170630_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(default=b'', max_length=64)),
                ('description', models.TextField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=b'', max_length=256)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, default=b'', null=True)),
                ('published', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Category')),
                ('full_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='travel_with_friends.FullTripTable')),
                ('outside_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='travel_with_friends.OutsideTripTable')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=64, null=True)),
                ('author', models.CharField(blank=True, default=b'', max_length=64, null=True)),
                ('about', models.TextField(blank=True, default=b'', null=True, verbose_name=b'About page (markdown)')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name=b'Google results description (ideally under 160 characters)')),
                ('keywords', models.TextField(blank=True, max_length=512)),
                ('description_social', models.TextField(blank=True, max_length=512)),
                ('image_social', models.ImageField(default=b'/media/img/social-card.png', upload_to=b'img/')),
                ('analytics', models.CharField(blank=True, default=b'', max_length=64, null=True, verbose_name=b'Google Analytics tracking nuber (UA-XXXXXXXX).')),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(default=b'', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='username_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
