# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_friends', '0003_outsideroutetable_outsidetriptable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poidetailtablev2',
            table='poi_detail_table',
        ),
    ]
